config/routes.rb
Rails.application.routes.draw do

  post 'support' => 'friendships#support', as: :support
  post 'unsupport' => 'friendships#unsupport', as: :unsupport

  resources :posts do
    resources :comments
  end

  resources :events  do
    resources :posts
  end

  resources :volunteers

  resources :contacts, only: [:new, :create]

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks"}

  root 'events#index'
  get 'join_volunteer' => 'events#join_volunteer', as: :join_volunteer
  get 'disjoin_volunteer' => 'events#disjoin_volunteer', as: :disjoin_volunteer
  get 'contacts/new', :to => 'contacts#new'
  post 'contact', :to => 'contacts#contact'
  get 'event_list', :to => 'events#event_list'

end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @volunteers = Volunteer.all
    respond_with(@volunteers)
  end

  def show
    respond_with(@volunteer)
  end

  def new
    @volunteer = Volunteer.new
    respond_with(@volunteer)
  end

  def edit
  end

  def create
    @volunteer = Volunteer.new(volunteer_params)
    @volunteer.save
    respond_with(@volunteer)
  end

  def update
    @volunteer.update(volunteer_params)
    respond_with(@volunteer)
  end

  def destroy
    @volunteer.destroy
    respond_with(@volunteer)
  end

  private
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    def volunteer_params
      params.require(:volunteer).permit(:name,:image)
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<%= form_for(@volunteer) do |f| %>
  <% if @volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% @volunteer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/volunteers/edit.html.erb
<h1>Editing volunteer</h1>

<%= render 'form' %>

<%= link_to 'Show', @volunteer %> |
<%= link_to 'Back', volunteers_path %>

app/views/volunteers/index.html.erb
<h1>Listing volunteers</h1>

<table>
  <tbody>
    <% @volunteers.each do |volunteer| %>
      <tr>
        <th><%= image_tag event.volunteer.url(:medium) %>
       <h3><%= volunteer.name %></h3></th>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/volunteers/new.html.erb
<h1>New volunteer</h1>

<%= render 'form' %>

<%= link_to 'Back', volunteers_path %>

app/views/volunteers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @volunteer.name %>
</p>

<%= link_to 'Edit', edit_volunteer_path(@volunteer) %> |
<%= link_to 'Back', volunteers_path %>