config/routes.rb
Rails.application.routes.draw do

  post 'support' => 'friendships#support', as: :support
  post 'unsupport' => 'friendships#unsupport', as: :unsupport

  resources :posts do
    resources :comments
  end

  resources :events  do
    resources :posts
  end

  resources :volunteers

  resources :contacts, only: [:new, :create]

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks"}

  root 'events#index'
  get 'join_volunteer' => 'events#join_volunteer', as: :join_volunteer
  get 'disjoin_volunteer' => 'events#disjoin_volunteer', as: :disjoin_volunteer
  get 'contacts/new', :to => 'contacts#new'
  post 'contact', :to => 'contacts#contact'
  get 'event_list', :to => 'events#event_list'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/contact_request.rb
class ContactRequest < ActiveRecord::Base
  validates_presence_of :name, :email, :company_name, :phone_number, :description

  after_save :send_notification
  private

  def send_notification
    ContactMailer.contact_request(self).deliver
    ContactMailer.contact_notification_mail(self).deliver
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users, join_table: :events_users
  has_many :posts
  has_attached_file :image, styles: { medium: "200x200#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :title,  :presence => true
  validates_attachment :image, presence: true
  validate :end_date_after_start_date?
  scope :this_months_event, lambda { where("event_date >= ? AND end_date <= ?", Time.zone.now.beginning_of_month, Time.zone.now.end_of_month) }

  def end_date_after_start_date?
    if end_date < start_time
      errors.add :end_date, "must be after start date"
    end
  end

  before_save do
    self.event_date = self.start_time
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many  :comments, dependent: :destroy
  belongs_to :user
  belongs_to :event
  validates :name,  :presence => true
  # validate :checkpost, :on => :create

  # def checkpost
  #   if  self.name.blank?.inspect
  #     errors.add(:name, "can't be in the blank")
  #   end
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_and_belongs_to_many :events, join_table: :events_users
  has_many :posts, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
  has_attached_file :image, styles: { medium: "150x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # validates_attachment :image, presence: true, unless: -> { from_omniauth? }
  validates :first_name, :last_name, :confirm_email, :presence => true, unless: -> { from_omniauth? }
  validates :email, confirmation: true
  def full_name
    self.first_name + " " + self.last_name
  end

  def last_name_initial
    self.first_name + " " + self.last_name[0] + '.'
  end

  private

  def from_omniauth?
    provider && uid
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@facebook.com").first
      if registered_user
        return registered_user
      else
        user = User.create!(provider:      auth.provider,
                            profile_image: auth["info"]["image"],
                            first_name:    auth["info"][:name].scan(/[\w'-]+/).first,
                            last_name:     auth["info"][:name].scan(/[\w'-]+/).last,
                            uid:           auth.uid,
                            email:         auth["info"]['email'],
                            password:      Devise.friendly_token[0, 20])
      end
    end
  end
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize, only: [:new, :create]
  respond_to :html

  def authorize
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end

  def new
    @comment = Comment.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    respond_to do |format|
      format.js
    end
    #redirect_to root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :join_volunteer, :disjoin_volunteers]
  before_filter :authorize, only: [:join_volunteer, :disjoin_volunteers]
  respond_to :html,:js

  def authorize
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end

  def index
    @users = User.all
    @events = Event.last(3)
    @post = Post.last
    @comments = @post.comments unless @post.nil?
    @last_six_users = User.last(6)
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  def join_volunteer
    event = Event.find(params[:id])
    current_user.events << event
    flash[:notice] = "Successfully Join"
    redirect_to event_path(event)
  end

  def disjoin_volunteer
    event = Event.find(params[:id])
    current_user.events << event
    current_user.events.delete(event)
    flash[:notice] = "Successfully DisJoin"
    redirect_to root_path
  end

  def event_list
    @event_list = Event.all
    @latest_month_event = Event.this_months_event
    render layout: 'fancybox'
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :event_date,:image, :start_time, :end_date)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:new, :create]
  respond_to :html

  def authorize
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @event = Event.find(params[:event_id])
    @post = @event.posts.new(post_params)
    @post.user_id = current_user.id
     if @post.save
      redirect_to root_path
     else
       redirect_to :back
     end
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :user_id, :event_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="MobileOptimized" content="320">
  <meta name="format-detection" content="telephone=no">
  <meta name="viewport" content="user-scalable=1.0,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
  <title>:: Glis ::</title>
  <!--Custom style css-->
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'style', 'media' %>
  <%#= image_tag('favicon.ico', alt: '') %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
</head>
<body>
<!--Main Wrapper Starts Here-->
<div id="wrapper">
  <!--Header Starts Here-->
    <%= render 'shared/header' %>
  <!--Header ends here-->

  <!--Middle content starts here-->
  <section id="midd-container">
    <% if user_signed_in? %>
      <!--new volunteer section-->
      <div class="user-prf-sec">
        <div class="fixed-wrapper">
          <div class="user-prf-row1">
            <div class="user-prf-left">
              <div class="vol-img-lft"> <%= image_tag 'vol-img.jpg', alt: '' %> </div>
              <div class="user-prf-left-cont">
                <h2>Jameson Welch</h2>
                <i class="add-icon"><%= image_tag 'add-icon.jpg', alt: '' %></i> <span>Los Angeles, CA</span>
                <p>Bacon ipsum dolor amet boudin bacon pancetta drumstick capicola brisket prosciutto sausage ball tip salami pork chop cupim shank swine. Ball tip meatball jowl pork chop picanha. Andouille beef leberkas ham hock pancetta. Ball tip salami jowl meatloaf beef rump pork belly tongue shank boudin pancetta. </p>
              </div>
            </div>
            <div class="user-prf-rgt"> <strong>Volunteered:</strong>
              <p><span>300</span> times</p>
              <p><span>1000</span> hours</p>
              <p><span style="display:block;">2136</span> Supporters </p>
            </div>
          </div>
          <div class="user-photos-row">
            <ul>
              <li><%= image_tag 'photo-img.jpg', alt: '' %></li>
              <li><%= image_tag 'photo-img.jpg', alt: '' %></li>
              <li><%= image_tag 'photo-img.jpg', alt: '' %></li>
              <li><%= image_tag 'photo-img.jpg', alt: '' %></li>
            </ul>
          </div>
        </div>
      </div>
      <!--new volunteer section ends-->
    <% else %>
      <div class="float-full social-network-row">
        <div class="fixed-wrapper">
          <div class="child-left"><%= image_tag('child-img.png', alt: '') %></div>
          <div class="social-net-rgt">
            <h1>A SOCIAL NETWORK</h1>
            <h2>FOR VOLUNTEERS</h2>
            <p>Here you can find new gigs to work on<br>
              and friends to work with and support you.</p>
          </div>
        </div>
      </div>
      <div class="float-full gray-box-row">
        <div class="fixed-wrapper">
          <p>“Bacon ipsum dolor amet boudin bacon pancetta drumstick capicola
            brisket prosciutto sausage ball tip salami pork chop cupim shank swine.”<br>
            -Some Butcher</p>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </section>
  <!--Middle content ends here-->

  <!--Footer Starts here-->
    <%= render 'shared/footer' %>
  <!--Footer ends here-->

  <!--Main Wrapper Ends Here-->
</body>
</html>

app/views/shared/_footer.html.erb
<footer id="bott-container">
  <div class="fixed-wrapper">
    <div class="foo-col-1"> <span>Glis, Inc. (888) 888-8888</span>
      <div class="social-foo"> <a href="#" target="_blank"><%= image_tag('fb-icon.png', alt: '') %></a> <a href="#" target="_blank"><%= image_tag('twitter-icon.png', alt: '') %></a> <a href="#" target="_blank"><%= image_tag('gplus-icon.png', alt: '') %></a> <a href="#" target="_blank"><%= image_tag('linked-icon.png', alt: '') %></a> </div>
      <!--<a href="#" class="btn-contact">Contact Us</a>-->
      <%= link_to 'Contact Us', {:controller => 'contacts', :action => 'new'}, data: { fancybox_width: 600 }, class: 'fancybox btn btn-success btn-contact', onclick: 'if(isMobile.any()){$("body").addClass("no-scroll");}' %>
    </div>
    <div class="footer-link">
      <ul>
        <li><a href="#">Home</a></li>
        <% if user_signed_in? %>
          <li><a href="#">Settings</a></li>
          <li><a href="#">Inbox</a></li>
        <% end %>
        <li><a href="#">Sitemap</a></li>
        <% if user_signed_in? %>
          <li><a href="#">Gigs</a></li>
        <% end %>
        <li><a href="#">Partners</a></li>
        <% if user_signed_in? %>
          <li><a href="#">My Profile</a></li>
        <% end %>
        <li><a href="#">Privacy Policy</a></li>
      </ul>
    </div>
    <div class="send-feedback"> <a href="#">SEND US <br>
      FEEDBACK<br>
      <i><%= image_tag('feedback-icon.png', alt: '') %></i> </a> </div>
    <p class="cpy-full">Glis, Inc. &copy; <%= Time.now.year %> | Developed by evibobevy</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header id="top-container">
  <div class="fixed-wrapper">
    <div class="logo"><%= image_tag('logo.png', alt: '') %></div>
    <div class="header-search">
      <form action="" method="get">
        <div class="hd-search-box">
          <input name="" type="text">
          <button class="search-icon"></button>
        </div>
        <span class="inspire-text">Inspire the world with good.</span>
      </form>
    </div>
    <% if user_signed_in? %>
      <div class="loged-rgt">
        <div class="after-login-icon">
          <ul>
            <li><a href="#"><img src="/assets/date-icon.png" alt=""></a></li>
            <li><a href="#"><img src="/assets/setting-icon.png" alt=""></a></li>
            <li><a href="#"><img src="/assets/email-icon.png" alt=""></a></li>
            <li><a href="#"><img src="/assets/add-icon.png" alt=""></a></li>
          </ul>
        </div>
        <div class="loged-user">
          <img src="/assets/after-user-img.jpg" alt="">
          <span>Jameson</span>
        </div>
        <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => 'after-login-icon' %>
      </div>
    <% else %>
      <!--After login right section-->
      <div class="header-rgt-btn">
        <!--<a href="#"><small>CHECK</small> <strong>NEW</strong> <small class="event-pos">EVENTS</small></a>-->
        <%= link_to raw("<small>CHECK</small> <strong>NEW</strong> <strong>GIGS</strong>"), event_list_path, data: {fancybox_width: 850}, class: 'fancybox btn btn-success', onclick: 'if(isMobile.any()){$("body").addClass("no-scroll");}' %>
        <!--<a href="#" class="join-today"><strong>JOIN</strong> <small>TODAY</small></a> </div>-->
        <%= link_to raw("<strong>JOIN</strong> <small>TODAY</small>"), new_user_registration_path, data: { fancybox_width: 600, autoSize: false }, class: 'fancybox btn btn-success join-today', onclick: 'if(isMobile.any()){$("body").addClass("no-scroll");}' %>
          <!--ends here-->
        <% end %>
      </div>
  </div>
</header>

app/views/simple_calendar/_calendar.html.erb
<%= javascript_include_tag 'jquery-1.11.0.min' %>
<div class="simple-calendar">
  <%= link_to "Previous", url_for(params.merge(start_date: date_range.first - 1.day)), remote: true %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", url_for(params.merge(start_date: date_range.last + 1.day)), remote: true %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_month_names")%></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
	<div>
	<div class="pre_next">
    <%= link_to "", url_for(params.merge(start_date: date_range.first - 1.day)), remote: true, class:'arrow_left', style: 'float: left; margin-top: 3px;"' %>
	  <h2 style="float:left;font-size: 22px;font-family: proxima_nova_rgbold;"><strong><%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %></strong> </h2>
	  <%= link_to "", url_for(params.merge(start_date: date_range.last + 1.day)), remote: true, class:'arrow_right', style: 'float: left; margin-top: 3px;"' %>
</div>
  <div class="event_title">
    <h1>Event Calendar </h1>
  </div>
	</div>
 <div>
	 <table class="dayname_header" style="border: 0px solid gray;margin-left: 198px; margin-bottom: 0;">
		 <tr>
		   <th>MON</th>
		   <th>TUES</th>
		   <th>WED</th>
		   <th>THURS</th>
		   <th>FRI</th>
		   <th>SAT</th>
		   <th>SUN</th>
		 </tr>
	 </table>
  <table class="table table-striped" style="border-collapse: separate;border-spacing: 8px;*border-collapse: expression('separate', cellSpacing = '10px');">
    <thead>
      <!--<tr>-->
        <!--&lt;!&ndash;<%# date_range.slice(0, 7).each do |day| %>&ndash;&gt;-->
          <!--&lt;!&ndash;&lt;!&ndash;<th><%#= I18n.t("date.abbr_day_names")[day.wday] %></th>&ndash;&gt;&ndash;&gt;-->
      <!--</tr>-->
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
      <% unless @latest_month_event.blank? %>
      <div class="latest_event">
        <% @latest_month_event.each do |latest_event|%>
          <h3> <%= latest_event.event_date.try(:strftime, '%b %dth, %Y') %> </h3>
          <h4><%= latest_event.title.titleize %></h4>
          <hr />
        <% end %>
      </div>
    <% end %>
    </tbody>
  </table>
</div>
<script>
	$(document).ready(function(){
		$( "td.day").css({"border-radius": "11px", "background": "#73AD21", "padding": "0px","height": "150px;"  });
		$( "td.day.today ").css({"border-radius": "11px", "background": "#89BBF5", "padding": "0px","height": "150px;"  });
	});
</script>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", url_for(params.merge(start_date: date_range.first - 1.day)), remote: true %>
  Week <%= start_date.strftime("%U").to_i %>
  <%= link_to "Next", url_for(params.merge(start_date: date_range.last + 1.day)), remote: true %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>