config/routes.rb
Rails.application.routes.draw do

  post 'support' => 'friendships#support', as: :support
  post 'unsupport' => 'friendships#unsupport', as: :unsupport

  resources :posts do
    resources :comments
  end

  resources :events  do
    resources :posts
  end

  resources :volunteers

  resources :contacts, only: [:new, :create]

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks"}

  root 'events#index'
  get 'join_volunteer' => 'events#join_volunteer', as: :join_volunteer
  get 'disjoin_volunteer' => 'events#disjoin_volunteer', as: :disjoin_volunteer
  get 'contacts/new', :to => 'contacts#new'
  post 'contact', :to => 'contacts#contact'
  get 'event_list', :to => 'events#event_list'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users, join_table: :events_users
  has_many :posts
  has_attached_file :image, styles: { medium: "200x200#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :title,  :presence => true
  validates_attachment :image, presence: true
  validate :end_date_after_start_date?
  scope :this_months_event, lambda { where("event_date >= ? AND end_date <= ?", Time.zone.now.beginning_of_month, Time.zone.now.end_of_month) }

  def end_date_after_start_date?
    if end_date < start_time
      errors.add :end_date, "must be after start date"
    end
  end

  before_save do
    self.event_date = self.start_time
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :join_volunteer, :disjoin_volunteers]
  before_filter :authorize, only: [:join_volunteer, :disjoin_volunteers]
  respond_to :html,:js

  def authorize
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end

  def index
    @users = User.all
    @events = Event.last(3)
    @post = Post.last
    @comments = @post.comments unless @post.nil?
    @last_six_users = User.last(6)
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  def join_volunteer
    event = Event.find(params[:id])
    current_user.events << event
    flash[:notice] = "Successfully Join"
    redirect_to event_path(event)
  end

  def disjoin_volunteer
    event = Event.find(params[:id])
    current_user.events << event
    current_user.events.delete(event)
    flash[:notice] = "Successfully DisJoin"
    redirect_to root_path
  end

  def event_list
    @event_list = Event.all
    @latest_month_event = Event.this_months_event
    render layout: 'fancybox'
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :event_date,:image, :start_time, :end_date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_calendar_table.html.erb
<%= month_calendar events: events do |date, events| %>
  <div style="border-radius: 50%; width: 25px; height: 25px; background: white; padding: 4px;">
   <%= date.strftime('%e') %>
  </div>
  <% events.each do |event| %>
    <div>
      <%#= event.title %>
    </div>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :required => true %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.date_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_post.html.erb
<% unless @post.blank? %>
  <%= social_share_button_tag(@post.name, :url => "http://guides.rubyonrails.org/association_basics.html", :image => @post.user.image, :'data-type' => 'photo') %>
	<%= image_tag @post.user.image.url(:thumb) %>
	<h2><%=@post.user.full_name + " volunteered for " %><%= @post.event.title %></h2>
  <% seconds = (TimeDifference.between(Time.now, Post.last.created_at).in_seconds.to_i) %>
			<% mm, ss = seconds.divmod(60) %>
	    <% hh, mm = mm.divmod(60) %>
	    <% dd, hh = hh.divmod(24)%>
  <strong><%= "%d days, %d hours, %d minutes and %d seconds" % [dd, hh, mm, ss] %> </strong>

  <h3><%= @post.name %></h3>
<% end %>

<% if @post.present? && @users.exists?(@post.user) %>
  <%= link_to 'Join', event_path(@post.event) %>
<% else %>
  <%= link_to 'Disjoin', new_user_registration_path %>
<% end %>

<% unless @post.blank?  %>
	<h4> Comments</h4>
		<% @post.comments.each do |comment|%>
			<%= comment.commenter %><br>
		<hr>
		<% end %>
<% end %>

app/views/events/_volunteers.html.erb
<h1 class="title-event">Top 6 Glis Volunteers</h1>
<table class="volunteer_list">
  <tbody>
  <% @volunteers.in_groups_of(2, false) do |volunteer| %>
    <tr>
      <% for vol in volunteer %>
        <td><%= image_tag vol.image.url(:medium) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/event_list.html.erb
<%= javascript_include_tag 'jquery-1.11.0.min' %>
<div id="events_calendar">
  <%= render partial: "calendar", locals: {events: @event_list} %>
</div>

app/views/events/event_list.js.erb
$('#calendar_page').html('<%= j render("events/calendar_table", :events => @event_list) %>');

app/views/events/index.html.erb
<!--<script src="assets/mediaelement-and-player.min.js"></script>-->
<!--<link rel="assets/stylesheet" href="mediaelementplayer.css"/>-->
<div class="volunteer-full float-full user-prf-vol">
  <div class="fixed-wrapper">
    <% unless user_signed_in? %>
      <div class="video_row">
        <!--<video width="100%" height="400" id="player1" controls>-->
          <!--<source src="https://www.youtube.com/watch?v=C0DPdy98e4c" source type="video/youtube" />-->
        <!--</video>-->
	      <div class="videoWrapper">
	      <!-- Copy & Pasted from YouTube -->
	        <iframe width="400" height="300" src="http://www.youtube.com/embed/n_dZNLr2cME?rel=0&hd=1" frameborder="0" allowfullscreen></iframe>
	      </div>
	    </div>
		 <% end %>
    <% if !user_signed_in? %>
      <div class="volunteer-row">
        <div class="vol-left-main">
          <h3 class="left-hd">Available Volunteer Gigs</h3>
          <% @events.each do |event| %>
            <div class="volunteer-lft">
              <div class="stay-icon"><% if event.image.present? %><%= image_tag event.image.url(:medium), alt: '' %><% else %><%= image_tag 'stay-icon.png', alt: '' %><% end %></div>
              <div class="stay-detail">
                <h5><%= event.title %></h5>
                <span class="date-small"><%= event.event_date.try(:strftime, '%B %d, %Y') %></span> <a href="#" class="btn-join">JOIN</a> </div>
            </div>
          <% end %>
        </div>
        <div class="volunteer-rgt">
          <h3 class="rgt-hd">Top 6 Glis Volunteers</h3>
          <% @last_six_users.in_groups_of(2, false) do |volunteer| %>
            <ul>
              <% for vol in volunteer %>
                <li>
                  <% if vol.image.present? %>
                    <%= image_tag vol.image.url(:medium), alt: '', style: 'height: 190px; width: 180px' %>
                  <% else %>
                    <%= image_tag 'no-img.jpg', alt: '', style: 'height: 190px; width: 180px' %>
                  <% end %>
                  <span class="vol-name-over"> <%= vol.last_name_initial %> </span>
                </li>
                <!--<li> <%#= image_tag('no-img.jpg', alt: '') %> <span class="vol-name-over"> &nbsp; </span> </li>-->
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="supports-block">
        <h3 class="left-hd">My Supporters: <span>2456</span></h3>
        <div class="prf-suppo-list">
          <ul>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
            <li> <%= image_tag 'user-support.jpg', alt: '' %> <span>John Smith</span> </li>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="vol-detail-row">
      <div class="vol-lft">
        <div class="vol-img-lft"> <%= image_tag @post.user.image.url(:medium) %></div>
        <% if user_signed_in? %>
        <% unless current_user.friendships.exists?(friend_id:@post.user) %>
          <%= link_to 'Support',support_path(:friend_id => @post.user), :method => :post, :class=>"btn-black"%>
        <% else %>
          <%= link_to 'Unsupport',unsupport_path(:friend_id => @post.user), :method => :post, :class=>"btn-black"%>
        <% end %>
        <% else %>
          <%= link_to 'Support', 'javascript:;', :class=>"btn-black", :onclick => 'alert("Please Sign Up to support this user.");'%>
        <% end %>
        <!--<a href="#" class="btn-black"> Support </a>-->
        <!--<a href="#" class="btn-black"> Spread </a>-->
        <%#= social_share_button_tag(@post.name, :popup => "true", :'data-type' => 'photo' , :url => "192.168.31.206:3000", :class => 'btn-black') %>
        <a class="btn-black" href="javascript:;" onclick="javascript:fbShare('<%= @post.event.image.url %>', '<%= @post.name %>', 'Facebook Share popup', '<%= @post.event.image.url %>', 520, 350)">Share</a>
        <% if user_signed_in? %>
          <%= link_to 'Join', {:controller => 'events', :action => 'show', :id => @post.event.id}, { class: 'btn-black' } %>
        <% else %>
          <%#= link_to 'Join', 'javascript:;', { class: 'btn-black' } %>
          <%= link_to 'Join', new_user_registration_path, data: { fancybox_width: 600 }, class: 'fancybox btn btn-success btn-black'%>
        <% end %>
        </div>
        <!--<a href="#" class="btn-black"> Support </a> <a href="#" class="btn-black"> Spread </a> <%#= link_to 'Join', class: 'btn-black' %><a href="#" class="btn-black"> Join </a> </div>-->
      <div class="vol-user-comment">
        <!--<h4>Jameson Welch <span>volunteered for</span> Habitat for Humanity</h4>-->
        <h4><%=@post.user.full_name %> <span>volunteered for</span> <%= @post.event.title %></h4>
        <% seconds = (TimeDifference.between(Time.now, Post.last.created_at).in_seconds.to_i) %>
        <% mm, ss = seconds.divmod(60) %>
        <% hh, mm = mm.divmod(60) %>
        <% dd, hh = hh.divmod(24)%>
        <!--<span class="day-time-row"><strong>3</strong> days ago for <strong>12</strong> hours</span>-->
        <span class="day-time-row"><strong><%= "%d days ago for %d hours" % [dd, hh] %> </strong></span>
        <p class="vol-desc"><%= @post.name %></p>
        <div class="vol-reply-sec">
          <ul>
            <li>
              <% unless @post.blank?  %>
                <% @comments = @post.comments.last(2) %>
                <% @comments.each do |comment|%>
                  <!--<div class="reply-img"> <%#= image_tag @post.user.image.url(:medium), style: 'height: 70px; width: 90px;' %></div>-->
                  <!--<div class="reply-desc">-->
                    <!--&lt;!&ndash;<h5>John Smith</h5>&ndash;&gt;-->
                    <!--<h5><%#= @post.user.full_name %></h5>-->
                    <!--&lt;!&ndash;<span>2 minutes ago</span>&ndash;&gt;-->
                    <!--<span><%#= time_ago_in_words(comment.created_at) + " ago" %></span>-->
                    <!--<p>-->
                      <%= render "comment", :comment => comment %>
                    <!--</p><br><hr>-->
                  <!--</div>-->
                <% end %>
              <% end %>
              <!--<div class="reply-img"> <%#= image_tag @post.user.image.url(:medium), style: 'height: 70px; width: 90px;' %></div>-->
              <!--<div class="reply-desc">-->
                <!--&lt;!&ndash;<h5>John Smith</h5>&ndash;&gt;-->
                <!--<h5><%#= @post.user.full_name %></h5>-->
                <!--<span>2 minutes ago</span>-->
                <!--<p>Bacon ipsum dolor amet boudin bacon pancetta drumstick capicola brisket-->
                  <!--prosciutto sausage ball tip salami pork chop cupim shank swine. […]</p>-->
              <!--</div>-->
            </li>
            <!--<li>-->
              <!--<div class="reply-img"> <%#= image_tag @post.user.image.url(:medium), style: 'height: 70px; width: 90px;' %></div>-->
              <!--<div class="reply-desc">-->
                <!--&lt;!&ndash;<h5>John Smith</h5>&ndash;&gt;-->
                <!--<h5><%#= @post.user.full_name %></h5>-->
                <!--<span>7 minutes ago</span>-->
                <!--<p>Bacon ipsum dolor amet boudin bacon pancetta drumstick capicola brisket-->
                  <!--prosciutto sausage ball tip salami pork chop cupim shank swine. […]</p>-->
              <!--</div>-->
            <!--</li>-->
          </ul>
          <div class="reply-form">
            <%= form_for([@post, @post.comments.build], remote: true) do |f| %>
            <div>
              <%= f.text_field :commenter, :required => true %>
              <% if user_signed_in? %>
                <%= f.button 'Reply', :class => 'btn-reply' %>
              <% else %>
                <%= f.button 'Reply', :class => 'btn-reply', :onclick => 'alert("Please Sign Up to comment on this event.");' %>
              <% end %>
            </div>
          <% end %>
            <!--<form action="" method="get">-->
              <!--<input name="" type="text">-->
              <!--<button class="btn-reply">Reply</button>-->
            <!--</form>-->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function fbShare(url, title, descr, image, winWidth, winHeight) {
    var winTop = (screen.height / 2) - (winHeight / 2);
    var winLeft = (screen.width / 2) - (winWidth / 2);
    window.open('http://www.facebook.com/sharer.php?s=100&p[title]=' + title + '&p[summary]=' + descr + '&p[url]=' + url + '&p[images][0]=' + image, 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight);
  }
</script>
<script>
	var player = new MediaElementPlayer('#player1');
</script>

app/views/events/index.js.erb
$("#events_calendar").html("<%= escape_javascript render(partial: "calendar", locals: {events: @events}) %>");

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag @event.image.url(:medium) %>
</p>

<%= render 'posts/form' %>
<%= link_to 'Back', root_path %>